export const WORKSPACES_MOCKUP = [
  {
    id: 0,
    title: "DS2.AI_ENG",
    created: "about 1 year ago",
    updated: "10 months ago",
    owner: "coo@dslab.global",
    disabled: false,
  },
  {
    id: 1,
    title: "DS2.AI_KOR",
    created: "about 1 year ago",
    updated: "10 months ago",
    owner: "coo@dslab.global",
    disabled: false,
  },
  {
    id: 2,
    title: "DSLAB.GLOBAL_KOR",
    created: "11 months ago",
    updated: "10 months ago",
    owner: "coo@dslab.global",
    disabled: false,
  },
  {
    id: 3,
    title: "DSLAB.GLOBAL_ENG",
    created: "11 months ago",
    updated: "10 months ago",
    owner: "coo@dslab.global",
    disabled: false,
  },
  {
    id: 4,
    title: "TALKNOTE_KO",
    created: "11 months ago",
    updated: "11 months ago",
    owner: "coo@dslab.global",
    disabled: false,
  },
  {
    id: 5,
    title: "CLICKAI",
    created: "over 2 years ago",
    updated: "over 1 year ago",
    owner: "dslab",
    disabled: true,
  },
];
